const PROJECTS = [
 {id:'hordfast', geo:['hordfast'], kat:'veg', status:'ikke',
  navn:'E39 Stord–Os (Hordfast, Ådland–Svegatjørn)', kommuner:'Stord, Tysnes, Bjørnafjorden',
  fase:'Statlig reguleringsplan på høring 22. juni–1. oktober 2026. I «utviklingsporteføljen» i NTP 2025–2036, uten byggestart i perioden.',
  kostnad:'53,7 mrd kr', kostnadNote:'2023-kr, Statens vegvesen april 2025. Reguleringsplanen: 52,3 mrd (2022-kr) for anbefalt alternativ C3-D1, 100 km/t.',
  stat:'23,7 mrd kr (63 %)', bom:'14,0 mrd kr (37 %)', finNote:'Fordeling fra Prop. 228 S (2020–2021), 2021-kr, av dagjeldende 37,7 mrd. Ny fordeling og takster er ikke fastsatt. 15 års bompengeperiode er lagt til grunn.',
  lengde:'55 km firefelts veg', lengdeNote:'100 km/t. Ca 30 km i dagen, 7 tunneler (Ostunnelen 7,7 km), Bjørnafjorden bru ca 5,5 km (flytebru), Langenuen bru ca 1,6 km.',
  reisetid:'Inntil 1 time kortere', reisetidNote:'Leirvik–Bergen fra ca 90 til ca 45 min kjøretid, mer medregnet ferjeventetid. Bergen–Stavanger mot 2 timer når hele E39 er ferjefri.',
  nytte:'NN −0,9 mrd kr, NNB −0,03', nytteNote:'EFFEKT 2024, 2023-kr, uten bompenger (reguleringsplanens planomtale). Eldre NTP-grunnlag (2022): NN +13,9 mrd, trafikantnytte 14,6 mrd.',
  kilder:[['Statens vegvesen: reguleringsplan på høring','https://www.vegvesen.no/nn/vegprosjekt/europaveg/e39stordos/nyheitsarkiv/reguleringsplanen-for-e39-stord-os-er-lagt-ut-pa-hoyringe/'],['Planomtale reguleringsplan (PDF)','https://www.vegvesen.no/globalassets/vegprosjekter/europavei/e39stordos/reguleringsplan-dokumenter/rp-25/e39-adland-svegatjorn_planomtale_.pdf'],['Prop. 228 S (2020–2021) finansiering','https://www.regjeringen.no/no/dokumenter/prop.-228-s-20202021/id2869992/'],['NRK: Så mykje vil Hordfast kosta','https://www.nrk.no/vestland/sa-mykje-vil-hordfast-pa-e39-mellom-bergen-og-stavanger-kosta-1.17376365']]},

 {id:'bokn', geo:['bokn_belt','bokn'], kat:'veg', status:'ikke',
  navn:'E39 Bokn–Bømlafjorden', kommuner:'Bokn, Tysvær (Rogaland), Sveio (Vestland)',
  fase:'Kommunedelplan på høring 9. februar–23. mars 2026, kommunale vedtak høsten 2026. Ikke prioritert i NTP 2025–2036 (35 mill kr planmidler 2024–25).',
  kostnad:'21,3 mrd kr', kostnadNote:'Alternativ 1 (anbefalt), 2024-kr inkl. mva. Alternativ 2: 24,4 mrd.',
  stat:'Ikke fastsatt', bom:'Ikke fastsatt', finNote:'Kommunedelplanen har ingen finansieringsplan. Bompengeandel avgjøres i en senere stortingsproposisjon.',
  lengde:'58,1 km firefelts veg', lengdeNote:'100 km/t. 55,2 km i dagen, 0,8 km tunnel, 2,2 km bru (7 bruer, Boknasundet bru 785 m). Dagens E39: 66 km.',
  reisetid:'Ca 30 min kortere', reisetidNote:'Arsvågen–Bømlafjordtunnelen. Transportmodell: lette biler −22 min, tunge −13 min.',
  nytte:'NN +1,2 mrd kr, NNB +0,11', nytteNote:'Alternativ 1, 2024-kr. Trafikantnytte 14,5 mrd. Alternativ 2: NN −2,9 mrd, NNB −0,23.',
  kilder:[['Statens vegvesen: kommunedelplan til høring','https://www.vegvesen.no/nn/vegprosjekt/europaveg/e39boknstord/nyhetsarkiv/kommunedelplan-e39-boknbomlafjorden-til-offentlig-hoyring-og-ettersyn/'],['Planomtale kommunedelplan (PDF)','https://www.vegvesen.no/globalassets/vegprosjekter/europavei/e39boknstord/kommunedelplan-dokument/plandokument/planomtale---kommunedelplan-e39-boknbomlafjorden-pdf-15-mb.pdf'],['Kart (ArcGIS Hub)','https://e39boknbomlafjorden-kart-vegvesen.hub.arcgis.com/']]},

 {id:'gullkista', geo:['gullkista'], kat:'veg', status:'ikke',
  navn:'E39 Reed–Sandane (Gullkista)', kommuner:'Gloppen',
  fase:'Detaljregulering under utarbeiding, ikke på høring. Nedskalert til tunnelen i mai 2025, nytt kostnadsanslag pågår. Ikke navngitt i NTP 2025–2036 (3 mill kr planmidler til E39 Sandane–Byrkjelo–Svarstad).',
  kostnad:'Ca 0,4 mrd kr', kostnadNote:'400 mill kr, 2023-kr (Statens vegvesens utgreiing E39 Grodås–Byrkjelo, des. 2024).',
  stat:'100 %', bom:'Ingen', finNote:'Statlig finansiert utbedringstiltak.',
  lengde:'Ca 1,5 km', lengdeNote:'Ca 650 m ny tunnel gjennom Gullkista og ca 850 m ny veg i dagen. Vegstandard H1, 9 m bredde.',
  reisetid:'Ikke beregnet', reisetidNote:'Tiltaket er begrunnet i trafikksikkerhet: bergvegg på den ene siden og stup ned i Breimsvatnet på den andre.',
  nytte:'Ikke funnet', nytteNote:'',
  kilder:[['Statens vegvesen: E39 Reed–Sandane','https://www.vegvesen.no/nn/vegprosjekt/europaveg/e39reedsandane/'],['NRK: Gloppen krev raskare utbetring','https://www.nrk.no/vestland/gloppen-politikarar-krev-raskare-e39-utbetring-i-breimsfjellet-1.17895478']]},

 {id:'arna', geo:['arna_veg','arna_bane'], kat:'bane', status:'ntp1',
  navn:'E16 og Vossebanen Arna–Stanghelle (fellesprosjekt)', kommuner:'Bergen, Vaksdal',
  fase:'Prioritert i første periode av NTP 2025–2036. Finansiering vedtatt av Stortinget 2025 (Prop. 97 S). Anleggsstart 2026, hovedtunnelkontrakter 2029. Veg ferdig 2037–38, bane 2038–39.',
  kostnad:'41,2 mrd kr', kostnadNote:'Styringsramme, 2025-kr. Kostnadsramme 49,3 mrd. Veg ca 48 %, bane ca 52 %.',
  stat:'Ca 37,0 mrd kr (90 %)', bom:'4,2 mrd kr (10 %)', finNote:'Bompenger kun på veg: 4 215 mill (2025-kr), 6 bomstasjoner, 75/150 kr, 15 år. Jernbanen er 100 % statlig.',
  lengde:'Ca 30 km veg + ca 30 km dobbeltspor', lengdeNote:'Tre lange vegtunneler (9–10 km hver), firefelt Arna–Trengereid. Arnatunnelen 19 km og Vaksdalstunnelen 8 km på bane, dimensjonert for 200 km/t.',
  reisetid:'Veg ca −10 min, tog ≥ −14 min', reisetidNote:'Arna–Stanghelle. Bergen–Voss med tog ned mot 40 min når hele K5 (til Voss) er bygd, mot 1 t 21 min i dag.',
  nytte:'NN −36,5 mrd kr, NNB −1,0', nytteNote:'Prop. 97 S (2024–2025), 2025-kr. Statens vegvesens prioriteringsoppdrag 2023: NNV −11,9 mrd (2024-kr), NNB −1,0.',
  kilder:[['Prop. 97 S (2024–2025)','https://www.regjeringen.no/no/dokumenter/prop.-97-s-20242025/id3094779/'],['Statens vegvesen: Fellesprosjektet Arna–Stanghelle','https://www.vegvesen.no/vegprosjekter/europaveg/e16banearnastanghelle'],['Kartfortelling (ArcGIS StoryMaps)','https://storymaps.arcgis.com/stories/5013735230bc4738869a8a04a344947b']]},

 {id:'vagsbotn', geo:['vagsbotn'], kat:'veg', status:'ntp2',
  navn:'E39 Vågsbotn–Klauvaneset (Nordhordlandstunnelen)', kommuner:'Bergen',
  fase:'Prioritert i NTP 2025–2036 med byggestart tidligst 2031. Kommunedelplan vedtatt 2022, reguleringsplan på høring sommeren 2026, bystyrevedtak 2027.',
  kostnad:'9,2 mrd kr', kostnadNote:'Styringsmål 2025 (økt 2,3 mrd siden 2023). NTP-grunnlaget: 6,9 mrd (2024-kr).',
  stat:'Ca 5,4 mrd kr', bom:'Ca 1,5–1,6 mrd kr', finNote:'Fordeling fra NTP-grunnlaget (6,9 mrd, 2024-kr). Bompenger via Bypakke Bergen. Fordeling av økningen til 9,2 mrd er ikke avklart.',
  lengde:'Ca 7,5 km firefelts veg', lengdeNote:'Herav ca 5 km tunnel.',
  reisetid:'Ikke oppgitt', reisetidNote:'',
  nytte:'NNB ca −0,7 til −1,0', nytteNote:'NNV ca −1,8 til −2,1 mrd (2024-kr, Statens vegvesens prioriteringsoppdrag). Tallene bør verifiseres mot originaltabellen.',
  kilder:[['Statens vegvesen: E39 Vågsbotn–Klauvaneset','https://www.vegvesen.no/vegprosjekter/europaveg/e39vagsbotnklauvaneset/'],['TU: Grønt lys for Nordhordlandstunnelen','https://www.tu.no/nyhetsstudio/regjeringen-gir-groent-lys-til-nordhordlandstunnelen/37825'],['NRK: NTP 2025–2036 i Vestland','https://www.nrk.no/vestland/ntp-2025_2036-i-vestland-1.16817220']]},

 {id:'fjosanger', geo:['fjosanger_arna'], kat:'veg', status:'skisse',
  navn:'E39 Ringveg øst Fjøsanger–Arna', kommuner:'Bergen',
  fase:'Tidlig planlegging («alternativ velges»), kommunedelplanarbeid under oppstart, naturkartlegging 2026. 9,9 mill kr planmidler i NTP 2025–2036. Linja i kartet er en skisse.',
  kostnad:'Ikke fastsatt', kostnadNote:'Eldre anslag: 17–20 mrd for hele Ringveg øst (2016), ca 19 mrd for tunnel Arna–Fjøsanger (2020).',
  stat:'Ikke fastsatt', bom:'Ikke fastsatt', finNote:'',
  lengde:'Ikke fastsatt', lengdeNote:'Lang tunnel mellom Arna og Fjøsanger/Sjølinjen er hovedkonseptet.',
  reisetid:'Ikke beregnet', reisetidNote:'',
  nytte:'Ikke beregnet', nytteNote:'',
  kilder:[['Statens vegvesen: E39 Fjøsanger–Arna','https://www.vegvesen.no/vegprosjekter/europaveg/e39fjosangerarna/'],['NRK: Ringveg øst vil kosta minst 17 milliardar (2016)','https://www.nrk.no/vestland/ringveg-ost-vil-kosta-minst-17-milliardar-1.13103850']]},

 {id:'bybanen', geo:['bybanen'], kat:'bybane', status:'ntp1',
  navn:'Bybanen til Åsane (byggetrinn 5)', kommuner:'Bergen',
  fase:'Reguleringsplan vedtatt 2023. Tunnel Sandviken–Sjøgaten valgt oktober 2024, omregulering av sentrumsdelen med planforslag høsten 2026. Byggestart tidligst 2028. NTP 2025–2036 har foreløpig midler til Fløyfjelltunnelen.',
  kostnad:'18,2 mrd kr (P50)', kostnadNote:'P85 21,4 mrd, eks. mva, 2023-kr (KS2 2024). Mulige kutt på inntil 7 mrd er utredet.',
  stat:'70 % av kollektivdelen', bom:'Ca 3 mrd kr (anslag)', finNote:'Statlig andel gjennom byvekstavtalen. NTP setter av 3,6 mrd til Fløyfjelltunnelen og holder resten tilbake til trasé er avklart. Lokal andel via Bypakke Bergen.',
  lengde:'12,7 km dobbeltspor', lengdeNote:'Kaigaten–Vågsbotn med 14 holdeplasser. Inkluderer forlenget Fløyfjelltunnel (ca 2,5 km), sykkelveg og veg.',
  reisetid:'Torget–Åsane terminal ca 17 min', reisetidNote:'Til Vågsbotn ca 25 min.',
  nytte:'Ikke funnet', nytteNote:'',
  kilder:[['Vestland fylkeskommune: kostnadsestimatet ligg fast','https://www.vestlandfylke.no/nyheitsarkiv/2024/kostnadsestimatet-for-bybanen-til-asane-ligg-fast/'],['Bybanen Utbygging: Sentrum–Åsane','https://www.bybanenutbygging.no/sentrum---asane/'],['NRK: Enighet om bybanetunnel','https://www.nrk.no/vestland/politisk-enighet-om-bybanetunnel-til-asane-i-bergen-og-vestland-1.17067162']]},

 {id:'floyfjell', geo:['floyfjell'], kat:'veg', status:'ntp1',
  navn:'E39 Fløyfjelltunnelen (forlenging nord og oppgradering sør)', kommuner:'Bergen',
  fase:'Del av Bybanen til Åsane. 3,6 mrd kr statlige midler i NTP 2025–2036.',
  kostnad:'Ca 3,4 mrd kr', kostnadNote:'Andel av bybaneanslaget 2022 (P50). NTP: 3,6 mrd.',
  stat:'100 %', bom:'Ingen', finNote:'Statlig riksvegtiltak i byvekstavtalen.',
  lengde:'Forlenging ca 2,5 km', lengdeNote:'Nytt løp nordover mot Eidsvåg og oppgradering av dagens tunnel, som frigjør dagens E39 i Sandviken til bybane.',
  reisetid:'Ikke oppgitt', reisetidNote:'',
  nytte:'Ikke oppgitt', nytteNote:'',
  kilder:[['Bergen kommune: kostnadsanslag fordelt på hovedelementer','https://www.bergen.kommune.no/hvaskjer/tema/presserom/pressemeldinger/bybanen-til-asane-oppdatert-kostnadsanslag-og-fordeling-pa-hovedelementer']]},

 {id:'sotra', geo:['sotra'], kat:'veg', status:'bygging',
  navn:'Rv 555 Sotrasambandet (OPS)', kommuner:'Bergen, Øygarden',
  fase:'Under bygging siden 2022. Åpning utsatt fra juni 2027 til 4. kvartal 2027, og per september 2026 uten ny dato. OPS-selskapet krever ca 5 mrd ekstra.',
  kostnad:'23,1 mrd kr', kostnadNote:'Totalt inkl. forberedende arbeider, 2022-kr. OPS-kontrakten 19,8 mrd. Stortingets øvre ramme (2018): 17 mrd.',
  stat:'10,5 mrd kr (62 %)', bom:'6,5 mrd kr (38 %)', finNote:'Prop. 41 S (2017–2018), 2018-kr. 20 års bompengeperiode, gjennomsnittstakst 39,50 kr (2017-kr).',
  lengde:'9,4 km firefelts veg', lengdeNote:'4 tunneler (ca 4,6 km), ny Sotrabru ca 950 m med hovedspenn 590 m, 14 km gang- og sykkelveg.',
  reisetid:'10–20 min i rushtid', reisetidNote:'KS2. Statens vegvesens NTP-dashbord: −3,4 min for lette biler.',
  nytte:'NN +2,1 mrd kr, NNB 0,4', nytteNote:'Prop. 41 S, 2017-kr. Statens vegvesens NTP-dashbord (kostnad 17,9 mrd): NN −0,5 mrd.',
  kilder:[['Statens vegvesen: Sotrasambandet','https://www.vegvesen.no/vegprosjekter/riksveg/sotrabergen/'],['Prop. 41 S (2017–2018)','https://www.regjeringen.no/contentassets/70f2cd375bbf45ce8ddbb285a3212383/nn-no/pdfs/prp201720180041000dddpdfs.pdf'],['NRK: Sotrasambandet forsinket nok en gang','https://www.nrk.no/vestland/sotrasambandet-forsinket-nok-en-gang-_-apner-ikke-i-2027-1.18020377']]},

 {id:'storehaugen', geo:['storehaugen'], kat:'veg', status:'ntp1',
  navn:'E39 Storehaugen–Førde (Hafstadfjelltunnelen)', kommuner:'Sunnfjord',
  fase:'Prioritert i første periode av NTP 2025–2036. Reguleringsplan vedtatt 2023. KS2 og bompengeproposisjon gjenstår. Mulig byggestart 2028.',
  kostnad:'4,6 mrd kr', kostnadNote:'Anslag 2026. NTP 2025–2036: 3,9 mrd (2024-kr). Statens vegvesen mai 2025: 4,1 mrd (2026-kr).',
  stat:'Ca 3,0 mrd kr', bom:'1,44 mrd kr', finNote:'Statlig bidrag ligger fast fra NTP; bompengeandelen er økt fra 0,93 til 1,44 mrd. Takst anslått ca 105 kr (fra ca 65).',
  lengde:'Ca 9,5 km ny E39', lengdeNote:'Tunnel 7,5–7,7 km Myra–Bruland gjennom Hafstadfjellet. Toplanskryss på Storehaugen.',
  reisetid:'10–15 min kortere', reisetidNote:'Statens vegvesen. NTP-dashbord: −10,8 min lette biler.',
  nytte:'NN −2,2 mrd kr, NNB −0,6', nytteNote:'Statens vegvesens porteføljeprioritering mai 2025, 2026-kr. NTP-grunnlag: NN −1,8 mrd.',
  kilder:[['Statens vegvesen: E39 Storehaugen–Førde','https://www.vegvesen.no/vegprosjekter/europaveg/e39storehaugenforde/'],['NRK: Hafstadfjelltunnelen blir ein halv milliard dyrare','https://www.nrk.no/vestland/firda_-hafstadfjelltunnelen-blir-ein-halv-milliard-dyrare-1.17822458'],['SVV porteføljeprioritering mai 2025 (PDF)','https://www.vegvesen.no/contentassets/57a396aa72dc4f9aa0a126ecf887f413/portefoljeprioritering_-mai-2025.pdf']]},

 {id:'vikafjellet', geo:['vikafjellet'], kat:'veg', status:'ikke',
  navn:'Rv 13 Vikafjellet (Vikafjellstunnelen)', kommuner:'Vik, Voss',
  fase:'Ikke i NTP 2025–2036, ingen finansiering. Ansvar for rv 13 Vinje–Sogndal overført fra Nye Veier til Statens vegvesen i 2025. Tunnellinja i kartet er en skisse mellom kjente portalområder.',
  kostnad:'3,8 mrd kr', kostnadNote:'2023-kr inkl. mva (Vista Analyse for Nye Veier). 3,1 mrd i 2019-kr.',
  stat:'Ikke avklart', bom:'Ikke avklart', finNote:'',
  lengde:'14,9 km tunnel + 2,3 km utbedring', lengdeNote:'Hola (Myrkdalen) – Bøadalen/Tistel (Vik). Erstatter 26,1 km fjellovergang, 8,9 km kortere.',
  reisetid:'16 min kortere', reisetidNote:'Fra 29 til 13 min over fjellet, og helårs vegforbindelse.',
  nytte:'Netto nåverdi −2,3 mrd kr', nytteNote:'2023-kr, åpning 2030 forutsatt (Vista Analyse 2023).',
  kilder:[['Vista Analyse: Vikafjellstunnelen (PDF)','https://www.regjeringen.no/contentassets/f517f097ff11468fbb8087f6bc981c43/nvas/vedlegg-vikafjellstunnelen.pdf'],['NRK: Vikafjellstunnelen framleis ute av NTP','https://www.nrk.no/vestland/vikafjellstunnelen-er-framleis-ute-av-ntp_-_-dei-drit-i-oss-1.16818248']]},

 {id:'rv13_djupevik', geo:['rv13_djupevik'], kat:'veg', status:'bygging',
  navn:'Rv 13 Djupevik–Kviturtunnelen (Nye Veier)', kommuner:'Ullensvang',
  fase:'Under bygging. Veiutbyggingsavtale med Samferdselsdepartementet signert november 2023, Nye Veiers første avtale for en utbedringsstrekning. Risa AS fikk totalentreprisen høsten 2024, anleggsstart februar 2025 og ferdigstilling høsten 2026. Neste etappe, rv 13 Freim–Djupevik på 550–600 m, er lyst ut med anleggsperiode 2026–2027.',
  kostnad:'408 mill kr', kostnadNote:'Forventet byggekostnad i veiutbyggingsavtalen, 2023-kr. Totalentreprisen til Risa AS er på ca 200 mill kr eks. mva. Oppdatert kostnadsanslag er ikke offentliggjort.',
  stat:'Statlig', bom:'Ingen', finNote:'Finansiert over veiutbyggingsavtalen mellom Samferdselsdepartementet og Nye Veier. Ingen bompenger er vedtatt på strekningen. Nøyaktig statlig andel i prosent er ikke oppgitt.',
  lengde:'1,2–1,5 km veg', lengdeNote:'Kontrakten omfatter 1,2 km ny veg i dagen, utvidet med 260 m til ca 1,5 km. Veiutbyggingsavtalen oppgir 1,3 km. Ny veg i skjering på fjellsiden, 7,5 m bred. Dagens veg blir gang- og sykkelveg mot Odda. To korte bruer, kulvert, natursteinsmurer og skredsikringsgjerder. Ingen ny tunnel. Strekningen går fra Djupevik nordover til sørportalen på Kviturtunnelen.',
  reisetid:'Ingen gevinst beregnet', reisetidNote:'Formålet er trafikksikkerhet og færre stengninger ved steinsprang, ikke kortere reisetid. Raspunktet Byrkjeneset ligger midt på strekningen.',
  nytte:'Ikke offentliggjort', nytteNote:'Nye Veier oppgir i årsrapporten for 2024 at utbedringsstrekningene på rv 13 og E136 ikke inngår i selskapets tabell over netto nytte per budsjettkrone. Ingen egen analyse er publisert.',
  kilder:[['Nye Veier: Rv 13 Djupevik–Kviturtunnelen','https://www.nyeveier.no/strekninger/rv-13-skare-voss/rv-13-djupevik-kviturtunnelen/'],['Regjeringen: veiutbyggingsavtale signert','https://www.regjeringen.no/no/aktuelt/samferdselsdepartementet-har-signert-vegutbyggingsavtale-med-nye-veier-for-strekninga-rv.-13-djupevikkviturtunnelen/id3016424/'],['Nye Veier: Risa AS skal skredsikre og utbedre rv 13','https://www.nyeveier.no/nyheter/risa-as-skal-skredsikre-og-utbedre-rv-13-i-ullensvang/'],['Regjeringen: rv 13 Vinje–Sogndal tilbake til Statens vegvesen','https://www.regjeringen.no/no/aktuelt/statens-vegvesen-overtek-ansvaret-for-rv.-13-mellom-vinje-og-sogndal/id3084424/']]},

 {id:'erdal', geo:['erdal'], kat:'veg', status:'ntp2',
  navn:'Rv 5 Erdal–Naustdal', kommuner:'Sunnfjord, Kinn',
  fase:'Kommunedelplan vedtatt 2023, reguleringsplan under arbeid. Prioritert i andre periode av NTP 2025–2036 (2031–2036).',
  kostnad:'3,4 mrd kr', kostnadNote:'NTP 2025–2036, 2024-kr. Statens vegvesen mai 2025: 3,5 mrd (2026-kr).',
  stat:'100 %', bom:'Ingen', finNote:'Statlig finansiert skredsikringsprosjekt.',
  lengde:'6,7 km tunnel', lengdeNote:'Smedneset (Erdal) – Jarane (Naustdal). Vegen blir 1,3 km kortere.',
  reisetid:'Ikke oppgitt', reisetidNote:'Hovedformålet er skredsikring langs Førdefjorden.',
  nytte:'NN −2,8 mrd kr, NNB −1,0', nytteNote:'Statens vegvesens porteføljeprioritering mai 2025, 2026-kr.',
  kilder:[['Statens vegvesen: Rv 5 Erdal–Naustdal','https://www.vegvesen.no/vegprosjekter/riksveg/rv5erdalnaustdal/'],['SVV porteføljeprioritering mai 2025 (PDF)','https://www.vegvesen.no/contentassets/57a396aa72dc4f9aa0a126ecf887f413/portefoljeprioritering_-mai-2025.pdf']]},

 {id:'bogstunnelen', geo:['bogstunnelen'], kat:'veg', status:'ikke',
  navn:'E39 Bogstunnelen–Gaular grense', kommuner:'Høyanger',
  fase:'Kommunedelplan 2015. Ikke prioritert i NTP 2025–2036. Separat oppgradering av dagens Bogstunnel 2024–2027.',
  kostnad:'Ca 1,1 mrd kr', kostnadNote:'1 125 mill i NTP 2022–2033 (andre periode); prisår usikkert.',
  stat:'Ikke avklart', bom:'Ikke avklart', finNote:'',
  lengde:'4,2 km tunnel', lengdeNote:'Bogen–Ytredalen, forbi Vadheim.',
  reisetid:'Ikke funnet', reisetidNote:'',
  nytte:'Ikke funnet', nytteNote:'',
  kilder:[['NRK: Vegvesenet går for tunnel forbi Vadheim','https://nrk.no/sognogfjordane/vegvesenet-gar-for-tunnel-forbi-vadheim-1.12261548'],['Statens vegvesen: E39 Bogstunnelen (oppgradering)','https://www.vegvesen.no/vegprosjekter/prosjekt/e39bogstunnelen/']]},

 {id:'roldal', geo:['roldal'], kat:'veg', status:'bygging',
  navn:'E134 Røldal–Seljestad', kommuner:'Ullensvang',
  fase:'Under bygging, første salve september 2025. Åpning planlagt 2030/2031. Hovedentreprenør Bertelsen & Garpestad gikk konkurs i 2026.',
  kostnad:'5,4 mrd kr', kostnadNote:'Kostnadsramme 5 360 mill (2026-kr) vedtatt juni 2026. Opprinnelig styringsramme 4,1 mrd og kostnadsramme 4,9 mrd (2024-kr, Prop. 44 S).',
  stat:'3,4 mrd kr (83 %)', bom:'0,69 mrd kr (17 %)', finNote:'Prop. 44 S (2023–2024), 2024-kr. Takst 91 kr lette / 273 kr tunge, ca 15 år. Overskridelser dekkes av staten.',
  lengde:'Ca 12,4 km tunnel + 2,9 km i dagen', lengdeNote:'Ny Røldalstunnel Liamyrane–Seljestad. Vegen blir 6,4 km kortere med ca 1 000 m mindre stigning.',
  reisetid:'12 min (lette), 18 min (tunge)', reisetidNote:'Prop. 44 S.',
  nytte:'NN −1,7 mrd kr, NNB −0,5', nytteNote:'2024-kr, med bompenger (Prop. 44 S). Uten bompenger: −1,3 mrd.',
  kilder:[['Prop. 44 S (2023–2024)','https://www.regjeringen.no/no/dokumenter/prop.-44-s-20232024/id3022843/'],['Statens vegvesen: E134 Røldal–Seljestad','https://www.vegvesen.no/nn/vegprosjekt/europaveg/e134vagsliseljestad/e134roldalseljestad/'],['AT.no: 342 millioner ekstra etter konkurs','https://www.at.no/anlegg/etter-bg-konkursen-regjeringen-ber-om-342-millioner-ekstra-til-e134/1270964']]},

 {id:'hylland', geo:['hylland'], kat:'veg', status:'ntp2',
  navn:'E16 Hylland–Slæen (Nærøydalen)', kommuner:'Aurland, Voss',
  fase:'Reguleringsplan vedtatt 2016, planendring på høring 2026. NTP 2025–2036 legger midler i 2031–2036. Rangert som nr 1 i Statens vegvesens porteføljeprioritering mai 2025.',
  kostnad:'2,5 mrd kr', kostnadNote:'Styringsmål, 2024-kr. Planendring (2025) skal spare ca 200 mill.',
  stat:'100 %', bom:'Ingen', finNote:'Statlig finansiert skredsikringsprosjekt.',
  lengde:'6,3 km tunnel', lengdeNote:'Erstatter Stalheims- og Sivletunnelen. Vegen forkortes fra 10 til 8 km.',
  reisetid:'Ikke oppgitt', reisetidNote:'Ca 2 km kortere veg.',
  nytte:'Ikke funnet', nytteNote:'Statens vegvesen omtaler NNB som «midt på treet».',
  kilder:[['Statens vegvesen: E16 Hylland–Slæn','https://www.vegvesen.no/nn/vegprosjekt/europaveg/e16hyllandslan/'],['NRK: Vegvesenets porteføljeoversikt','https://www.nrk.no/vestland/statens-vegvesen-sin-portefoljeoversikt_-29-nye-prosjekt-som-skal-prioriterast-dei-neste-ara-1.17423096']]},

 {id:'klakegg', geo:['klakegg'], kat:'veg', status:'ntp2',
  navn:'E39 Klakegg–Byrkjelo (skredsikring Våtedalen)', kommuner:'Sunnfjord, Gloppen',
  fase:'På vent. NTP 2025–2036 legger byggestart til 2031–2036. Ingen aktiv planlegging.',
  kostnad:'Ikke funnet', kostnadNote:'',
  stat:'Statlig', bom:'Ingen', finNote:'',
  lengde:'Ikke oppgitt', lengdeNote:'Skredsikring mot snø- og sørpeskred gjennom Våtedalen.',
  reisetid:'Ikke oppgitt', reisetidNote:'Stengt veg gir omkjøring på flere titalls mil for tungtransport.',
  nytte:'Ikke funnet', nytteNote:'',
  kilder:[['Statens vegvesen: E39 Klakegg–Byrkjelo','https://www.vegvesen.no/nn/vegprosjekt/europaveg/e39klakeggbyrkjelo/']]},

 {id:'strynefjellet', geo:['strynefjellet'], kat:'veg', status:'ntp1',
  navn:'Rv 15 Strynefjellet (med arm til Geiranger)', kommuner:'Stryn (Vestland), Skjåk (Innlandet), Stranda (Møre og Romsdal)',
  fase:'Prioritert i første periode av NTP 2025–2036. Planprogram fastsatt 2026, trasévalg 2027, byggestart 2030, åpning 2036. Linja i kartet er en skisse etter KVU-konsept B1.',
  kostnad:'5,9 mrd kr', kostnadNote:'NTP 2025–2036, 2024-kr. Statens vegvesen mai 2025: 6,1 mrd (2026-kr). Inkl. Geiranger-armen anslått til over 9 mrd (2025).',
  stat:'100 %', bom:'Ingen', finNote:'Fullfinansiert av staten i NTP.',
  lengde:'Hovedtunnel 15,6–20,5 km', lengdeNote:'Skåre/Hjelledalen–Breidalen. Arm mot Geiranger 6,5–8,2 km. Erstatter Oppljos-, Grasdals- og Ospelitunnelen.',
  reisetid:'12 min kortere', reisetidNote:'Statens vegvesens gjennomføringsplan 2026–2031.',
  nytte:'NN −4,6 mrd kr, NNB −0,9', nytteNote:'Statens vegvesens porteføljeprioritering mai 2025, 2026-kr.',
  kilder:[['Statens vegvesen: Rv 15 Strynefjellet','https://www.vegvesen.no/nn/vegprosjekt/riksveg/rv15strynefjellet/'],['NRK: Ny riksvei 15 vil koste over 9 milliarder','https://www.nrk.no/innlandet/ny-riksvei-15-vil-koste-over-9-milliarder-kroner-1.17659249']]},

 {id:'byrkjelo_grodas', geo:['byrkjelo_grodas'], kat:'veg', status:'ikke',
  navn:'E39 Byrkjelo–Grodås (Nordfjord)', kommuner:'Gloppen, Stryn, Volda',
  fase:'Kommunedelplan vedtatt 2019/2020. Ikke i NTP 2025–2036, på vent. Statens vegvesen anbefaler i mellomtiden 3,1 mrd i utbedring av dagens E39.',
  kostnad:'11,4 mrd kr', kostnadNote:'Hele strekningen, 2018-kr (±25 %). Byrkjelo–Svarstad: 8,9 mrd.',
  stat:'Ikke avklart', bom:'Ikke avklart', finNote:'',
  lengde:'Ca 36 km ny veg', lengdeNote:'Utvikfjellet tunnel 6,8 km, hengebru Frøholm–Svarstad 1 760 m.',
  reisetid:'Ca 1 t → 25–27 min', reisetidNote:'Byrkjelo–Grodås, ferjefritt.',
  nytte:'Ikke funnet', nytteNote:'',
  kilder:[['Statens vegvesen: E39 Byrkjelo–Grodås','https://www.vegvesen.no/vegprosjekter/europaveg/e39byrkjelogrodas/nyheitsarkiv/e39-byrkjelogrodas-klar-for-neste-etappe/'],['NRK: Store vegplanar i Nordfjord','https://www.nrk.no/vestland/store-vegplanar-i-nordfjord-1.17166913']]},

 {id:'stad', geo:['stad'], kat:'sjo', status:'bygging',
  navn:'Stad skipstunnel', kommuner:'Stad',
  fase:'Kontrakt med AF Gruppen signert august 2026 etter at regjeringen først foreslo å skrinlegge prosjektet. Byggestart tidlig 2027, byggetid ca 5 år.',
  kostnad:'8,6 mrd kr', kostnadNote:'Kostnadsramme inkl. mva vedtatt juni 2026. Kontrakt ca 5,6 mrd eks. mva. Opprinnelig 4,1 mrd (2021-kr).',
  stat:'100 %', bom:'Ingen', finNote:'Statlig (Nærings- og fiskeridepartementet, Kystverket).',
  lengde:'1,7 km tunnel', lengdeNote:'2,2 km inkl. ledestrukturer. 50 m høy, 36 m bred. Kjødepollen–Moldefjorden.',
  reisetid:'Ikke tallfestet i minutter', reisetidNote:'Nytte i form av redusert ventetid og bedre regularitet forbi Stadhavet (verdsatt til ca 0,3 mrd i 2021).',
  nytte:'NN −6,6 mrd kr, NNB −0,95', nytteNote:'Kystverket november 2025. 2021: −2,4 mrd.',
  kilder:[['Kystverket: Signerte kontrakten','https://www.kystverket.no/nyheter/signerte-kontrakten-for-byggingen-av-stad-skipstunnel/'],['Regjeringen: Nytt kostnadsanslag 8,6 mrd','https://www.regjeringen.no/no/aktuelt/nytt-kostnadsanslag-for-stad-skipstunnel-86-milliarder-kroner/id3152574/'],['NRK: Så ulønnsam er Stad skipstunnel','https://www.nrk.no/vestland/ny-analyse-fra-kystverket_-sa-ulonnsam-er-stad-skipstunnel-1.17628033']]},
];
